name: Waka Stats

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 23:00 UTC daily
    - cron: '0 23 * * *'

jobs:
  update-readme:
    name: Update this repo's README with weekly activity
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: true
          SHOW_TITLE: true
